# Generated by Django 5.1.6 on 2025-02-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarian', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veterinarian',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='veterinarianspecialization',
            old_name='specialization_id',
            new_name='specialization',
        ),
        migrations.RenameField(
            model_name='veterinarianspecialization',
            old_name='veterinarian_id',
            new_name='veterinarian',
        ),
    ]
