# Generated by Django 5.1.6 on 2025-02-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarian', '0002_rename_user_id_veterinarian_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='middle_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
