# Generated by Django 5.1.6 on 2025-02-23 03:32

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarian', '0005_clinics_barangay_clinics_building_clinics_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinics',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClinicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='veterinarian.clinics')),
            ],
        ),
        migrations.DeleteModel(
            name='ClinicImages',
        ),
    ]
