# Generated by Django 5.1.6 on 2025-02-23 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarian', '0007_clinics_registered_at_clinicimages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinics',
            name='veterinarian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veterinarian.veterinarian'),
        ),
    ]
