# Generated by Django 5.1.6 on 2025-02-20 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_specializations_veterinarian_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinarianspecialization',
            name='specialization_id',
        ),
        migrations.RemoveField(
            model_name='veterinarian',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='veterinarianspecialization',
            name='veterinarian_id',
        ),
        migrations.DeleteModel(
            name='Specializations',
        ),
        migrations.DeleteModel(
            name='Veterinarian',
        ),
        migrations.DeleteModel(
            name='VeterinarianSpecialization',
        ),
    ]
