# Generated by Django 5.1.6 on 2025-02-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_remove_veterinarianspecialization_specialization_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_veterinarian',
            field=models.BooleanField(default=False),
        ),
    ]
